#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

# Exit on any error
set -e

maindir="@CMAKE_SOURCE_DIR@"
bdir="@CMAKE_BINARY_DIR@"
dest="@CMAKE_BINARY_DIR@/fatpart"
tc="@TCROOT@"
archgcc="@ARCH_GCC_TC@"
strip="@CMAKE_STRIP@"
gcctc="@GCC_TOOLCHAIN@"
host_arch="@HOST_ARCH@"
arch="@ARCH@"
spc="@FATPART_CLUSTER_SIZE@" # sectors per cluster
arch_dir="@TCROOT_ARCH_DIR@"
host_arch_dir_sys="@HOST_DIR@"
mtools_ver="@VER_MTOOLS@"
busybox_ver="@VER_BUSYBOX@"
fbdoom_ver="@VER_FBDOOM@"
lua_ver="@VER_LUA@"
micropython_ver="@VER_MICROPYTHON@"
treecmd_ver="@VER_TREECMD@"
tcc_ver="@VER_TCC@"

if [[ "@HOST_ARCH@" != "i386" ]]; then
   if [ -f "$gcctc/$archgcc-linux-strip" ]; then
      strip="$gcctc/$archgcc-linux-strip"
   fi
else
   if [ ! -f "$strip" ]; then
      strip="/usr/bin/env strip"
   fi
fi

mtoolsdir=$host_arch_dir_sys/mtools/$mtools_ver
busybox_dir=$arch_dir/busybox/$busybox_ver
fbdoom_dir=$arch_dir/fbdoom/$fbdoom_ver
lua_dir=$arch_dir/lua/$lua_ver
micropython_dir=$arch_dir/micropython/$micropython_ver
treecmd_dir=$arch_dir/treecmd/$treecmd_ver
tcc_dir=$arch_dir/tcc/$tcc_ver

mformat=$mtoolsdir/mformat
mlabel=$mtoolsdir/mlabel
mmd=$mtoolsdir/mmd
mcopy=$mtoolsdir/mcopy
mdel=$mtoolsdir/mdel

function strip_binary {
   $strip -s "$1"
}

function pushd {
   command pushd "$@" > /dev/null
}

function popd {
   command popd "$@" > /dev/null
}

function link_or_copy {
   if [ -n "$AZURE_HTTP_USER_AGENT" ]; then
      cp $1 $2
   else
      ln $1 $2
   fi
}

function create_fatpart {
   # Always (re)create the file because fathack --truncate shrinks it, and
   # mformat would then format the small file with the wrong geometry.
   dd status=none if=/dev/zero of=$dest bs=1M count=@INITRD_SZ_MB@
}

function format_fatpart {
   # mformat options
   # -d <N> ; num of FAT copies
   # -F     ; force FAT32 to be used
   # -c <N> ; sectors per cluster
   # -T <N> ; total sectors

   local force_fat32=""

   if [[ "$spc" == "1" ]]; then
      force_fat32="-F"
   fi

   $mformat -i $dest -d 1 $force_fat32 -c $spc -T @INITRD_SZ_SEC@ ::
   $mlabel -i $dest ::TILCK
}

function create_sysroot_skeleton {

   # Remove the sysroot directory created by the previous build
   rm -rf $bdir/sysroot

   # Check if the sysroot directory contains any paths with whitespaces,
   # because we don't support that and it's better to fail with a graceful
   # error, in case someone places such a file/directory there.
   if [ -n "$(find $maindir/sysroot -name "* *")" ]; then
      echo "-----------------------------------------------------------------"
      echo "ERROR: $maindir/sysroot contains paths with whitespaces "
      echo "ERROR: and that is not supported. Here's the list of such paths:"
      echo
      find $maindir/sysroot -name "* *"
      echo "-----------------------------------------------------------------"
      exit 1
   fi

   # Copy our skeleton sysroot/ directory to the configured build directory
   # so that in the next steps we can fill it with build-generated artifacts
   # like binaries and libraries.
   cp -r $maindir/sysroot $bdir/

   # Enter in the temporary sysroot directory for this build
   cd $bdir/sysroot

   # Remove the README file that is not supposed to be in the actual sysroot
   rm README
}

# Copy the shell-script extra system tests in <SYSROOT>/usr/local/tests
function add_script_tests {
   mkdir -p usr/local/tests
   cp $maindir/tests/system/scripts/* ./usr/local/tests
}

function add_apps {

   IFS=";"
   local all_apps="$(cat $bdir/userapps/list.txt)"

   for x in ${all_apps[@]}; do

      local name=$(basename -- $x)
      local dest_dir="usr/bin"

      if [[ "$name" == "init" ]]; then

         dest_dir="bin"

      elif [[ "$name" == "devshell" ]]; then

         add_script_tests
      fi

      cp "$x" $dest_dir
      strip_binary "$dest_dir/$name"

   done
   unset IFS
}

function add_busybox {

   if [[ "@USERAPPS_busybox@" == "0"   ||
         "@USERAPPS_busybox@" == "off" ||
         "@USERAPPS_busybox@" == "OFF" ||
         "@USERAPPS_busybox@" == "false" ]]
   then
      return
   fi

   if [ -d $busybox_dir ]; then
      link_or_copy $busybox_dir/busybox bin/
   else
      echo "BUSYBOX NOT FOUND at $busybox_dir/busybox!!!"
   fi
}

function add_fat_test_dir {

   if [[ "@FAT_TEST_DIR@" == "0"   ||
         "@FAT_TEST_DIR@" == "off" ||
         "@FAT_TEST_DIR@" == "OFF" ||
         "@FAT_TEST_DIR@" == "false" ]]
   then
      return
   fi

   mkdir -p tdir
   pushd tdir
      for i in {0..99}; do
         if [ $i -lt 10 ]; then
            n="0"
         else
            n=""
         fi
         echo > test_$n$i
      done
   popd
}

function add_tcc {

   if [ -z "@EXTRA_TCC_ENABLED@" ]; then
      return
   fi

   local musl=@GCC_TC_SYSROOT@/lib

   mkdir -p lib/tcc
   cp -r $tcc_dir/include lib/tcc
   link_or_copy $tcc_dir/tcclib.h lib/tcc/include
   link_or_copy $tcc_dir/tcc bin/tcc
   cp -r $tcc_dir/examples lib/tcc-examples

   # TCC's --libpaths and --crtprefix were set to /lib/<arch>-tilck-musl at
   # configure time. Copy the minimum musl sysroot files TCC needs for static
   # linking, plus libtcc1.a, into that directory.
   local tcc_musl=lib/@ARCH_GCC_TC@-tilck-musl
   mkdir -p $tcc_musl
   link_or_copy $tcc_dir/libtcc1.a $tcc_musl
   for f in crt1.o crti.o crtn.o; do
      link_or_copy $musl/$f $tcc_musl
   done

   # Copy libc.a and strip its debug info. The musl archive ships with full
   # DWARF debug sections (~18 MB on riscv64, ~4 MB on i386). Stripping them
   # brings it down to a reasonable size for the initrd.
   cp $musl/libc.a $tcc_musl
   $strip --strip-debug $tcc_musl/libc.a
}

function add_micropython {

   if [ -z "@EXTRA_MICROPYTHON_ENABLED@" ]; then
      return
   fi

   link_or_copy $micropython_dir/ports/unix/build-standard/micropython usr/bin
}

function add_fbdoom {

   if [ -z "@EXTRA_FBDOOM_ENABLED@" ]; then
      return
   fi

   mkdir -p usr/lib/fbDOOM
   link_or_copy $fbdoom_dir/fbdoom/fbdoom.gz usr/lib/fbDOOM

   if [ -f $fbdoom_dir/Doom1.WAD ]; then
      local wadfile="$fbdoom_dir/Doom1.WAD"
   else
      local wadfile="$fbdoom_dir/freedoom/freedoom1.wad.gz"
   fi

   link_or_copy "$wadfile" usr/lib/fbDOOM

   # Here document

   (
cat <<'EOF'
#!/bin/sh

# Exit on failure
set -e
fbdoomgz="/usr/lib/fbDOOM/fbdoom.gz"
wadgz="/usr/lib/fbDOOM/freedoom1.wad.gz"
fbdoom="/tmp/fbdoom"

if [ -f /usr/lib/fbDOOM/Doom1.WAD ]; then
   wad="/usr/lib/fbDOOM/Doom1.WAD"
else
   wad="/tmp/freedom1.wad"
fi

if ! [ -f $fbdoomgz ]; then
   echo "ERROR: fbDOOM binary $fbdoomgz not found."
   exit 1
fi

if ! [ -f $fbdoom ]; then
   echo -n "Uncompressing ${fbdoomgz}... "
   cp $fbdoomgz /tmp
   gunzip -c /tmp/fbdoom.gz > $fbdoom
   chmod 755 $fbdoom
   rm /tmp/fbdoom.gz
   echo "[ OK ]"
fi

if ! [ -f $wad ]; then

   if ! [ -f $wadgz ]; then
      echo "ERROR: Wad file $wadgz not found."
      exit 1
   fi

   echo -n "Uncompressing ${wadgz}... "
   cp $wadgz /tmp
   gunzip -c /tmp/freedoom1.wad.gz > $wad
   rm /tmp/freedoom1.wad.gz
   echo "[ OK ]"
fi

echo "Running $fbdoom -iwad $wad"
exec $fbdoom -iwad $wad
EOF
   ) > usr/bin/fbdoom

   chmod 755 usr/bin/fbdoom
}


function add_vim {

   local vimdir="$arch_dir/vim/@VER_VIM@"

   if [ -z "@EXTRA_VIM_ENABLED@" ]; then
      return
   fi

   mkdir -p usr/lib/vim
   link_or_copy $vimdir/install/vim.gz usr/lib/vim
   link_or_copy $vimdir/install/vr.tgz usr/lib/vim

   mkdir -p usr/lib/vim/samples
   cp $maindir/tests/interactive/vim_text_files/* usr/lib/vim/samples/
}

function add_tree_cmd {

   if [ -z "@EXTRA_TREE_CMD_ENABLED@" ]; then
      return
   fi

   link_or_copy $treecmd_dir/tree usr/bin
}

function add_lua {

   if [ -z "@EXTRA_LUA_ENABLED@" ]; then
      return
   fi

   if [ -f $lua_dir/src/lua ]; then
      link_or_copy $lua_dir/src/lua bin/
   fi

   if [ -f $lua_dir/src/luac ]; then
      link_or_copy $lua_dir/src/luac bin/
   fi
}

function add_extra_apps {
   for manifest in $bdir/userapps/extra/*/manifest.txt; do
      if [ ! -f "$manifest" ]; then
         continue
      fi
      while IFS= read -r line; do
         if [ -z "$line" ]; then
            continue
         fi
         local name=$(basename -- "$line")
         if [ -f "$line" ]; then
            cp "$line" usr/bin
            strip_binary "usr/bin/$name"
         fi
      done < "$manifest"
   done
}

function make_fatpart {

   create_fatpart
   format_fatpart

   # first, create the directories
   for f in $(find * -type d); do
      $mmd -i $dest $f
   done

   # [debug] Create a hole (file that will be deleted later) in the fatpart.
   # [debug] This forces the bootloaders to run fat_compact_clusters() and do
   # [debug] some real work. Otherwise, fat_calculate_used_bytes() will return
   # [debug] the same as fat_get_first_free_cluster_off() and we won't test
   # [debug] that fat_compact_clusters() really works.
   if ! [ -f hole ]; then
      dd status=none if=/dev/zero of=hole bs=1K count=16
   fi
   $mcopy -i $dest hole ::/hole
   # [end debug]

   # then, copy all the files in sysroot
   for f in $(find * -type f); do

      if [[ "$(basename -- $f)" == ".gitignore" ]]; then
         continue;
      fi

      # [debug] Skip our hole file
      if [[ "$(basename -- $f)" == "hole" ]]; then
         continue;
      fi
      # [end debug]

      $mcopy -i $dest $f ::/$f
   done

   # [debug] Delete our hole file
   $mdel -i $dest ::/hole
}

# -----------------------------------------------------------------------------
# MAIN
# -----------------------------------------------------------------------------

create_sysroot_skeleton

add_apps
add_fat_test_dir
add_busybox
add_tcc
add_micropython
add_fbdoom
add_vim
add_tree_cmd
add_lua
add_extra_apps

make_fatpart
