trigger:
  branches:
    exclude:
      - readme*
      - temp-*
      - exp-*

  paths:
    include:
      - 'scripts/build_toolchain'
      - 'scripts/pkgmgr/**'
    exclude:
      - 'README.md'
      - '*.md'

pool:
  vmImage: 'ubuntu-22.04'


container: 'vvaltchev/archlinux:v7'

variables:
  RUNNING_IN_CI: 1
  GTEST_SHUFFLE: 0
  ARCH: i386

steps:
  - script: printenv
    displayName: Dump env
  - script: sudo -E ./scripts/build_toolchain
    displayName: "Install pkgs"
  - script: sudo -E ./scripts/build_toolchain -s gtest
    displayName: "Build gtest"
  - script: sudo -E ./scripts/build_toolchain -s lcov
    displayName: "Build lcov"
  - script: sudo -E ./scripts/build_toolchain -s libmusl
    displayName: "Download libmusl"
  - script: sudo -E ./scripts/build_toolchain -s ncurses
    displayName: "Build ncurses"
  - script: sudo -E ./scripts/build_toolchain -s vim
    displayName: "Build vim"
  - script: sudo -E ./scripts/build_toolchain -s tfblib
    displayName: "Build tfblib"
  - script: sudo -E ./scripts/build_toolchain -s lua
    displayName: "Build lua"
  - script: sudo -E ./scripts/build_toolchain -s treecmd
    displayName: "Build treecmd"
  - script: make -j
    displayName: Build the kernel
  - script: make -j gtests
    displayName: Build the unit tests
  - script: ./build/gtests
    displayName: Run the unit tests
  - script: ./tests/runners/ci_run_all_tests_wrapper -c
    displayName: Run the system tests
