#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause

############################################
# CONSTANTS

VERSION_REGEX='[0-9]+[.][0-9]+[.][0-9]+([.][0-9]+)*'

if [ -t 1 ]; then

   # We're running on a terminal, so we can use colors

   RED='\033[0;31m'
   GREEN='\033[0;32m'
   BROWN='\033[0;33m'
   BLUE='\033[0;34m'
   MAGENTA='\033[0;35m'
   CYAN='\033[0;36m'
   LGRAY='\033[0;37m'
   DGRAY='\033[1;37m'
   LRED='\033[1;31m'
   LGREEN='\033[1;32m'
   YELLOW='\033[1;33m'
   LBLUE='\033[1;34m'
   LMAGENTA='\033[1;35m'
   LCYAN='\033[1;36m'
   WHITE='\033[1;37m'
   RATTRS='\033[0m'

else

   RED=''
   GREEN=''
   BROWN=''
   BLUE=''
   MAGENTA=''
   CYAN=''
   LGRAY=''
   DGRAY=''
   LRED=''
   LGREEN=''
   YELLOW=''
   LBLUE=''
   LMAGENTA=''
   LCYAN=''
   WHITE=''
   RATTRS=''
fi

if [ -n "$TRAVIS" ]; then

   if [[ $QUIET != 1 ]]; then
      echo "CI Detected: TRAVIS"
   fi
   export RUNNING_IN_CI=1

elif [ -n "$CIRCLECI" ]; then

   if [[ $QUIET != 1 ]]; then
      echo "CI Detected: CIRCLE"
   fi

   export RUNNING_IN_CI=1

elif [ -n "$AZURE_HTTP_USER_AGENT" ]; then

   if [[ $QUIET != 1 ]]; then
      echo "CI Detected: AZURE PIPELINES"
   fi
   export RUNNING_IN_CI=1

else

   if [[ $QUIET != 1 ]]; then
      if [[ "$RUNNING_IN_CI" == "1" ]]; then
         echo "CI Detected: UNKNOWN"
      else
         echo "CI Detected: None [Assuming user machine]"
      fi
   fi
fi

############################################
# FUNCTIONS

# $1 version in the format "major.minor.patchlevel"
# $2 component number to get (1 => major, 2 => minor, 3 => patchlevel)
function get_version_comp {
   echo -ne $1 | grep -Eo '[0-9]+' | head -$2 | tail -1
}

# $1 = program name
function generic_get_version_str {
   $1 --version | head -1 | grep -Eo "${VERSION_REGEX}[ ]*$" | head -1
}

# $1 = command
function run_command {
   echo "Running command: $1"
   eval "$1"
}

# $1 = command
# $2 = output file
function run_command2 {
   echo "Running command: $1 &> $2"
   eval "$1 &> $2"
}

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

function show_work_on_component_msg {
   echo
   echo "*** $1 ***"
   echo
}

function show_skip_component_msg {
   echo "NOTE: Skipping $1"
}

# $1 = program name
# $2 = min version string
function show_too_old_and_exit {
   echo "System's $1 is too old. Version >= $2 is required."
   exit 1
}

# $1 = program name
# $2 = current version string (i.e. "1.2.3")
# $3 = min version string (i.e. "1.2.3")
function fail_if_too_old {

   major=$(get_version_comp $2 1)
   minor=$(get_version_comp $2 2)
   echo "[cmake_run] $1 version (parsed): $major.$minor"

   min_major=$(get_version_comp $3 1)
   min_minor=$(get_version_comp $3 2)

   if [[ $major -lt $min_major ||
         ( $major -eq $min_major && $minor -lt $min_minor ) ]]
   then
      show_too_old_and_exit $1 $3
   fi
}

function download_file_in_cache {

   local url="$1"
   local remote_file="$2"
   local local_file="$3"

   if [[ "$local_file" == "" ]]; then
      local_file="$remote_file"
   fi

   if ! [ -f $TC/cache/$local_file ]; then

      pushd $TC/cache
      mkdir -p tmp
      pushd tmp

      rm -rf *
      wget "$url/$remote_file"

      if ! [ -f "$remote_file" ]; then
         echo "ERROR: download of $local_file ($remote_file) failed"
         exit 1
      fi

      mv "$remote_file" "../$local_file"
      popd

      rmdir tmp
      popd

   else

      if [[ "$remote_file" == "$local_file" ]]; then
         echo "NOTE: Skipping the download of $local_file"
      else
         echo "NOTE: Skipping the download of $local_file ($remote_file)"
      fi
   fi
}

function extract_cachefile_tar_generic {

   local tarfile="$1"
   local internalDirName="$2"
   local newDirName="$3"
   local tarOpt=""

   if [[ "$tarfile" == *.gz ]]; then
      tarOpt="xfz"
   elif [[ "$tarfile" == *.bz2 ]]; then
      tarOpt="xfj"
   elif [[ "$tarfile" == *.xz ]]; then
      tarOpt="xfJ"
   elif [[ "$tarfile" == *.tgz ]]; then
      tarOpt="xfz"
   else
      echo "ERROR: extension of '$tarfile' not supported!"
      exit 1
   fi

   echo "Extracting $tarfile..."
   tar $tarOpt $TC/cache/$tarfile

   if ! [ "$internalDirName" = "--" ]; then
      if ! [ "$internalDirName" = "$newDirName" ]; then

         if ! [ -d "$internalDirName" ]; then
            echo "ERROR: internal dir: '$internalDirName' not found"
            exit 1
         fi

         if [ -d "$newDirName" ]; then
            if [[ "$( ls -A $newDirName )" != "" ]]; then
               echo "ERROR: new dir: '$newDirName' exists and it's non-empty"
               exit 1
            else
               rmdir "$newDirName"  # new dir is empty, it's OK to remove
            fi
         fi

         mv "$internalDirName" "$newDirName"
      fi
   fi

   echo "Extracting completed."
}

function extract_cachefile_tar_gz {
   extract_cachefile_tar_generic "$1" "$2" "$3"
}

function extract_cachefile_tar_bz {
   extract_cachefile_tar_generic "$1" "$2" "$3"
}

function extract_cachefile_tar_xz {
   extract_cachefile_tar_generic "$1" "$2" "$3"
}

function download_git_repo_in_cache {

   local url="$1"
   local tag="$2"
   local tarname="$3"
   local dirname="$4"

   if [ -f $TC/cache/$tarname ]; then
      return
   fi

   if [ -z "$tag" ]; then

      git clone --depth 1 "$url" $dirname

   else

      if ! git clone --branch "$tag" --depth 1 "$url" $dirname; then

         # Git clone failed. There could be several reasons for that:
         #
         #     - The remote git server is down
         #
         #     - The pointed branch/tag/commit does not exist anymore because
         #       the ref has been deleted or the history has been rewritten.
         #
         #     - In some corner cases, like BitBucket, fetching individual
         #       untagged commits is not allowed. This is the only case for
         #       which an actual workaround is possible.
         #       See: https://stackoverflow.com/a/51002078/2077198
         #

         if echo "$tag" | grep -E "^[0-9a-z]+$"; then

            # It's worth trying this approach only if the tag looks like a
            # commit SHA.

            if git clone "$url" $dirname; then

               cd $dirname

               if ! git checkout "$tag"; then
                  echo "ERROR: the git ref $tag does not exist anymore!"
                  exit 1
               fi

               # Save the git commit info before deleting the .git directory
               git rev-parse --abbrev-ref HEAD > .ref_name
               git rev-parse --short HEAD > .ref_short
               git rev-parse HEAD > .ref
               echo "$tag" > .our_tag

               # Delete the .git directory which is not needed anymore and takes
               # quite some space. We just need one commit, not the whole
               # git history.
               rm -rf .git

               # Go back to the parent directory
               cd ..
            fi
         fi
      fi
   fi

   if ! [ -d "$dirname" ]; then
      echo "ERROR: git clone failed for: $url"
      exit 1
   fi

   tar cfz $tarname $dirname

   if ! [ -f $tarname ]; then
      echo "ERROR: tar failed"
      exit 1
   fi

   mv $tarname $TC/cache || exit 1
   rm -rf $dirname
}

function dump_cross_compiler_env {

   echo "[DEBUG] CC=$CC" >> $1
   echo "[DEBUG] CXX=$CXX" >> $1
   echo "[DEBUG] SYS_CC=$SYS_CC" >> $1
   echo "[DEBUG] SYS_CXX=$SYS_CXX" >> $1
   echo "[DEBUG] CC_POST_FLAGS=$CC_POST_FLAGS" >> $1
   echo "[DEBUG] CROSS_COMPILE=$CROSS_COMPILE" >> $1
   echo "[DEBUG] CFLAGS=$CFLAGS" >> $1
   echo "[DEBUG] LDFLAGS=$LDFLAGS" >> $1
   echo "[DEBUG] CPPFLAGS=$CPPFLAGS" >> $1

   for a in i386 i686 x86_64 riscv64 aarch64; do
      if which ${a}-linux-gcc &> null; then
         echo "[DEBUG] ${a}-linux-gcc: $(which ${a}-linux-gcc)" >> $1
      else
         echo "[DEBUG] ${a}-linux-gcc: " >> $1
      fi
   done
   echo "[DEBUG] PATH: $PATH" >> $1
}

function do_common_cross_compiler_setup {
   : # do nothing
}

