#!/bin/sh

echo
echo "Early /bin/sh bootstrap"
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
OS="`uname -s`"
BASH="bash"
SED="sed"
GREP="grep"

echo "Full args list: $0 $@"
echo "Detected host OS: $OS"
echo

if [ "$OS" = "FreeBSD" ]; then
   SED="gsed"
   GREP="ggrep"
fi

missing=0
for c in $BASH $SED $GREP; do
   echo -n "Check for tool: GNU $c "
   if command -v "$c" >/dev/null; then
      echo "[ OK ]"
   else
      echo "[ MISSING ]"
      missing=1
   fi
done

if [ $missing -eq 1 ]; then
   echo
   echo "ERROR: Some necessary GNU tools are missing on the system."
   echo "Please install the missing tools and re-run this script."
   echo
   exit 1
fi

if ! command -v bash > /dev/null; then
   echo "ERROR: Bash not found. Please install Bash and re-run this script."
   exit 1
fi

set -e
echo
echo "Determine this script's parent directory using realpath and dirname..."
THIS_SCRIPT="`realpath $0`"
THIS_DIR="`dirname $THIS_SCRIPT`"
BASH_SCRIPT="$THIS_DIR/bash_build_toolchain"

echo "THIS_SCRIPT: $THIS_SCRIPT"
echo "THIS_DIR:    $THIS_DIR"
echo "BASH_SCRIPT: $BASH_SCRIPT"
set +e

if ! [ -f "$BASH_SCRIPT" ]; then
   echo "ERROR: bash script not found!"
   exit 1
fi

exec /usr/bin/env bash $BASH_SCRIPT "$@"
